export default [
  "ACTION_CLASS_COURSE_CLASS_ADD",
  "ACTION_COURSE_CLASS_EDIT",
  "VIEW_PROJECTS_SCREEN_EDIT_PROJECTS",
  "ACTION_ACTIVITIES_SCREEN_EDIT",
  "ACTION_ACTIVITY_SCREEN_ADD_ACTION",
  "VIEW_STUDENTS_PII_NOT_VISIBLE_CONCERN",
  "ACTION_FEEDBACK_TRIGGER_SCREEN_ADD_TRIGGER",
  "ACTION_FEEDBACK_TRIGGER_SCREEN_DELETE_TRIGGER",
  "ACTION_STUDENT_PROJECT_REMOVE",
  "ACTION_POST_SUBMISSIONS_SCREEN_ADD_POST",
  "ACTION_POST_SUBMISSIONS_SCREEN_UPDATE_DELETE_POST",
  "ACTION_MINDSET_ADD",
  "ACTION_MINDSET_UPDATE",
  "ACTION_MINDSET_QUESTION_ADD",
  "ACTION_MINDSET_QUESTION_DELETE"
];
