export const CONFIG_NAME_LIST = [
  "brand_details",
  "DND_Reasons",
  "DELIVERY_CHANNEL_OPS",
  "brand_details_byju",
  "COVER_UP_CLASS_CONFIG_OPS",
  "REASSIGN_LANGUAGE_BOOKING_ALLOWED",
  "RECURRING_BOOKING_CONFIG",
  "APP_BOOKING_MAP",
  "LEADERSHIP_LABELS",
  "LEAD_SOURCE_CONFIG",
  "OFFLINE_CAMPAIGNS_CONFIG",
  "TEACHER_CHANGE_DISPOSITIONS",
  "CREDIT_CHANGE_DISPOSITIONS",
  "DST_ON_COUNTRIES",
  "CLASS_TYPE_CONFIG",
  "CLASS_NUMBER_FORMAT"
];
