export default [
  "PAGE_DASHBOARD",
  "ACTION_STUDENTS_AUTO_LOGIN",
  "PAGE_REPORTED_CONTENT",
  "PAGE_STUDENTS",
  "PAGE_STUDENT_DETAILS",
  "PAGE_EVENTS",
  "PAGE_CONTEST",
  "PAGE_DAILY_CONTEST",
  "PAGE_CHALLENGES",
  "PAGE_DAILY_CONTEST_CHALLENGES",
  "ACTION_STUDENTS_CALL_LOGS",
  "PAGE_CALL_LOGS"
];
