export default [
  "PAGE_DASHBOARD",
  "PAGE_STUDENTS",
  "PAGE_STUDENT_DETAILS",
  "PAGE_CONCENTRIX",
  "PAGE_SESSIONS",
  "PAGE_WHERE_BY",
  "PAGE_LIVE_CLASS",
  "PAGE_VIEW_FILE",
  "PAGE_CALL_LOGS",
  "PAGE_SYKES"
];
