export default [
  "PAGE_DASHBOARD",
  "PAGE_CLASSES",
  "PAGE_COURSES",
  "PAGE_PROJECTS",
  "PAGE_ACTIVITIES",
  "PAGE_COURSE_VERSION",
  "PAGE_QUIZ",
  "PAGE_VIEW_FILE",
  "PAGE_CALL_LOGS",
  "PAGE_MINDSET"
];
