export default [
  "PAGE_DASHBOARD",
  "PAGE_CLASSES",
  "PAGE_COURSES",
  "PAGE_PROJECTS",
  "PAGE_COUNTRIES",
  "PAGE_REGIONS",
  "PAGE_CONFIG_DATA",
  "PAGE_FEATURE_CONFIG",
  "PAGE_FEATURE_CONFIG_DETAILS",
  "PAGE_ACTIVITIES",
  "PAGE_LANGUAGES",
  "PAGE_PAYMENT_PACKAGES",
  "PAGE_COURSE_ITEMS",
  "PAGE_WHERE_BY",
  "PAGE_LIVE_CLASS",
  "PAGE_VIEW_FILE"
];
