export default [
  "PAGE_DASHBOARD",
  "PAGE_STUDENTS",
  "PAGE_STUDENT_DETAILS",
  "PAGE_TEACHERS",
  "PAGE_TEACHER_DETAILS",
  "PAGE_MY_TASK",
  "PAGE_TASK",
  "PAGE_SESSIONS",
  "PAGE_TEACHERS_SLOT_INFO",
  "PAGE_WHERE_BY",
  "PAGE_LIVE_CLASS",
  "PAGE_VIEW_FILE",
  "PAGE_CALL_LOGS"
];
