export default [
  "PAGE_DASHBOARD",
  "PAGE_STUDENT_DETAILS",
  "PAGE_MY_TASK",
  "PAGE_STUDENTS",
  "PAGE_WHERE_BY",
  "PAGE_LIVE_CLASS",
  "PAGE_VIEW_FILE",
  "PAGE_SLASH_RTC",
  "PAGE_CALL_LOGS"
];
